server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/,http://eureka7119:7119/eureka/,http://eureka7419:7419/eureka/
