#application.yml
server:
  port: 8002

#MyBatis config
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis配置文件所在路径
  type-aliases-package: top.aranlzh.springcloud.entities   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml      # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02            # 数据库名称
    username: myuser
    password: mypassword
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最小维持连接数
      initial-size: 5                                     # 初始化数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7119:7119/eureka,http://eureka7419:7419/eureka
  instance:
    instance-id: microservicecloud-dept8002 #自定义服务器名称信息
    prefer-ip-address: true #访问路径可以显示ip

info:
  app.name: aranlzh-microservicecloud
  company.name: www.aranlzh.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$